// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kttfvuncjgnlcnxchtsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dGZ2dW5jamdubGNueGNodHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjAyNTYsImV4cCI6MjA2MDIzNjI1Nn0.7HIvSZ-5zB4lEsQqpUUAAuhyeASF2LDkfPxPVz6Jd_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);